name: Build Wheels and sdist

on:
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install cibuildwheel
        run: |
          python -m pip install --upgrade pip
          pip install cibuildwheel==2.12.1

      - name: Build wheels
        env:
          # Skip building on Python 2.7
          # Additionally, skip 32-bit Windows for now as MSVC needs seperate setup with different toolchain to do this
          # Refer: https://cibuildwheel.readthedocs.io/en/stable/cpp_standards/#windows-and-python-27
          CIBW_SKIP: "*-win32"
          CIBW_ARCHS_MACOS: "x86_64 universal2 arm64" # build on M1 chip
          CIBW_BEFORE_TEST: "pip install -r {project}/tests/requirements.txt"
          CIBW_TEST_COMMAND: "pytest {project}/tests/python-tests"
        run: python -m cibuildwheel --output-dir ./dist

      - name: Store wheel artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: ./dist

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install build tool
        run: python -m pip install build

      - name: Build sdist
        run: python -m build --sdist --outdir ./dist

      - name: Store sdist artifact
        uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: ./dist

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DoozyX/clang-format-lint-action@v0.18.2
        with:
          source: "./include ./src"
          clangFormatVersion: 12